version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai_edu_postgres
    environment:
      POSTGRES_DB: ai_edu_platform
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: